[package]
name = "wasm_oss"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
embedded-nal-async = "0.8.0"
log = "0.4.25"
once_cell = "1.20.2"
reqwless = "0.13.0"

[dependencies.simple-async-local-executor]
version = "0.1.0"
default-features = false


