[workspace]
resolver = "2"
members = [
    "src/wasm_oss",
    "src/proto_rs",
]

[profile.release]
opt-level = "z"
debug = false
strip = true


[profile.dev]
opt-level = "z"
debug = false
strip = true
