[package]
name = "proto_rs"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
prost-derive = "0.13.5"

[build-dependencies]
prost-build = "0.13.5"